# Schreibt die drei kombinierten LaTeX-Tabellen ( escapingsicher)
setwd("C:/Users/HP/io/imf-replizierung")

bs <- "\"

writeLines(c(
  paste0("% LaTeX table fragment. Requires ", bs, "usepackage{booktabs,array}."),
  paste0(bs, "begingroup"),
  paste0(bs, "scriptsize"),
  paste0(bs, "setlength{", bs, "tabcolsep}{4pt}"),
  paste0(bs, "begin{center}"),
  paste0(bs, "begin{tabular}{l r r r r}"),
  paste0(bs, "toprule"),
  paste0("& ", bs, "multicolumn{1}{c}{Basis-FE} & ", bs, "multicolumn{1}{c}{Vollmodell-FE} & ", bs, "multicolumn{1}{c}{L", '\\"', "ander- und Jahres-FE} & ", bs, "multicolumn{1}{c}{DSV-GLS} ", bs, bs),
  paste0(bs, "midrule"),
  paste0("Fokuseffekt & unsc3 & unsc3 & unsc3 & unsc3 ", bs, bs),
  paste0("Koeffizient & $-$0.454 & 0.144 & $-$0.933 & 0.046 ", bs, bs),
  paste0("& (1.854) & (2.816) & (1.920) & (1.422) ", bs, bs),
  paste0(bs, "midrule"),
  paste0("Kontrollen & Laufzeit & DSV-Vollsatz & DSV-Vollsatz & DSV-Vollsatz ", bs, bs),
  paste0("L", '\\"', "ander-FE & Ja & Ja & Ja & Ja ", bs, bs),
  paste0("Jahres-FE & Nein & Nein & Ja & Nein ", bs, bs),
  paste0(bs, "midrule"),
  paste0("Beobachtungen & 514 & 282 & 281 & 282 ", bs, bs),
  paste0("L", '\\"', "ander & 116 & 69 & 69 & 58 ", bs, bs),
  paste0("L", '\\"', "ander mit unsc3 = 1 & 30 & 17 & 17 & 17 ", bs, bs),
  paste0("Jahre & 1992--2023 & 1992--2023 & 1992--2023 & 1992--2023 ", bs, bs),
  paste0(bs, "midrule"),
  paste0("R$^2$ (within) & 0.038 & 0.069 & 0.424 & -- ", bs, bs),
  paste0("F-Test (L", '\\"', "ander-FE) & 0.001 & 0.183 & 0.009 & -- ", bs, bs),
  paste0("Wooldridge-Test & 0.819 & 0.464 & 0.091 & -- ", bs, bs),
  paste0("Breusch-Pagan-Test & $<$0.001 & $<$0.001 & $<$0.001 & -- ", bs, bs),
  paste0(bs, "bottomrule"),
  paste0(bs, "end{tabular}"),
  paste0(bs, "end{center}"),
  paste0(bs, "noindent", bs, "footnotesize Robuste Standardfehler in Klammern. p-Werte der diagnostischen Tests. Die Zwei-Wege-FE-Spezifikation ist die vorab gew", '\\"', "ahlte Hauptspezifikation.", bs, "par"),
  paste0(bs, "endgroup")
), "latex/figures/phase_b/phase_b_h1_kombiniert.tex")

writeLines(c(
  paste0("% LaTeX table fragment. Requires ", bs, "usepackage{booktabs,array}."),
  paste0(bs, "begingroup"),
  paste0(bs, "scriptsize"),
  paste0(bs, "setlength{", bs, "tabcolsep}{4pt}"),
  paste0(bs, "begin{center}"),
  paste0(bs, "begin{tabular}{l r r r r}"),
  paste0(bs, "toprule"),
  paste0("& ", bs, "multicolumn{1}{c}{Basis-FE} & ", bs, "multicolumn{1}{c}{Vollmodell-FE} & ", bs, "multicolumn{1}{c}{L", '\\"', "ander- und Jahres-FE} & ", bs, "multicolumn{1}{c}{DSV-GLS} ", bs, bs),
  paste0(bs, "midrule"),
  paste0("Fokuseffekt & unsc3:resource", bs, "_dep & unsc3:resource", bs, "_dep & unsc3:resource", bs, "_dep & unsc3:resource", bs, "_dep ", bs, bs),
  paste0("Koeffizient & 0.060 & $-$0.055 & $-$0.111 & $-$0.014 ", bs, bs),
  paste0("& (0.078) & (0.132) & (0.103) & (0.067) ", bs, bs),
  paste0(bs, "midrule"),
  paste0("Kontrollen & Laufzeit & DSV-Vollsatz & DSV-Vollsatz & DSV-Vollsatz ", bs, bs),
  paste0("L", '\\"', "ander-FE & Ja & Ja & Ja & Ja ", bs, bs),
  paste0("Jahres-FE & Nein & Nein & Ja & Nein ", bs, bs),
  paste0(bs, "midrule"),
  paste0("Beobachtungen & 380 & 212 & 212 & 212 ", bs, bs),
  paste0("L", '\\"', "ander & 104 & 62 & 62 & 51 ", bs, bs),
  paste0("L", '\\"', "ander mit unsc3 = 1 & 27 & 16 & 16 & 16 ", bs, bs),
  paste0("Jahre & 1992--2023 & 1992--2023 & 1992--2023 & 1992--2023 ", bs, bs),
  paste0(bs, "midrule"),
  paste0("R$^2$ (within) & 0.027 & 0.101 & 0.486 & -- ", bs, bs),
  paste0("F-Test (L", '\\"', "ander-FE) & $<$0.001 & 0.100 & 0.021 & -- ", bs, bs),
  paste0("Wooldridge-Test & 0.747 & 0.261 & 0.064 & -- ", bs, bs),
  paste0("Breusch-Pagan-Test & $<$0.001 & $<$0.001 & $<$0.001 & -- ", bs, bs),
  paste0(bs, "bottomrule"),
  paste0(bs, "end{tabular}"),
  paste0(bs, "end{center}"),
  paste0(bs, "noindent", bs, "footnotesize Robuste Standardfehler in Klammern. Die Zwei-Wege-FE-Spezifikation ist die vorab gew", '\\"', "ahlte Hauptspezifikation.", bs, "par"),
  paste0(bs, "endgroup")
), "latex/figures/phase_b/phase_b_h2_kombiniert.tex")

writeLines(c(
  paste0("% LaTeX table fragment. Requires ", bs, "usepackage{booktabs,array}."),
  paste0(bs, "begingroup"),
  paste0(bs, "scriptsize"),
  paste0(bs, "setlength{", bs, "tabcolsep}{4pt}"),
  paste0(bs, "begin{center}"),
  paste0(bs, "begin{tabular}{l r r r}"),
  paste0(bs, "toprule"),
  paste0("& ", bs, "multicolumn{1}{c}{Basis-FE} & ", bs, "multicolumn{1}{c}{Vollmodell-FE} & ", bs, "multicolumn{1}{c}{L", '\\"', "ander- und Jahres-FE} ", bs, bs),
  paste0(bs, "midrule"),
  paste0("Fokuseffekt & unsc3:resource", bs, "_dep & unsc3:resource", bs, "_dep & unsc3:resource", bs, "_dep ", bs, bs),
  paste0("Koeffizient & 6.61e-04 & 5.01e-05 & $-$1.93e-06 ", bs, bs),
  paste0("& (5.00e-04) & (7.02e-04) & (4.96e-04) ", bs, bs),
  paste0(bs, "midrule"),
  paste0("Kontrollen & Laufzeit & DSV-Vollsatz & DSV-Vollsatz ", bs, bs),
  paste0("L", '\\"', "ander-FE & Ja & Ja & Ja ", bs, bs),
  paste0("Jahres-FE & Nein & Nein & Ja ", bs, bs),
  paste0(bs, "midrule"),
  paste0("Beobachtungen & 380 & 212 & 212 ", bs, bs),
  paste0("L", '\\"', "ander & 104 & 62 & 62 ", bs, bs),
  paste0("L", '\\"', "ander mit unsc3 = 1 & 27 & 16 & 16 ", bs, bs),
  paste0("Jahre & 1992--2023 & 1992--2023 & 1992--2023 ", bs, bs),
  paste0(bs, "bottomrule"),
  paste0(bs, "end{tabular}"),
  paste0(bs, "end{center}"),
  paste0(bs, "noindent", bs, "footnotesize Robuste Standardfehler in Klammern. Die Analyse ist explorativ.", bs, "par"),
  paste0(bs, "endgroup")
), "latex/figures/phase_b/phase_b_h4_kombiniert.tex")

cat("Alle drei Tabellen geschrieben.\n")
